// Portfolio Data - Single source of truth
// Update this file to change the website content

const portfolioData = {
	profile: {
		name: "Tom Sloan",
		headline: "Applied AI Engineer",
		tagline: "I design hardware, train models, and ship the software that connects them. Right now I'm teaching a robotic arm to pick things up by watching me do it first.",
		location: "Ottawa, Ontario, Canada",
		image: "images/profile/tom-sloan-profile.png",
		about: [
			"Robot Vision Engineer working with SLAM, computer vision, and drone-based 3D mapping. I use AWS, Docker, Python, and embedded systems daily. I keep building projects in autonomous systems and AI because I can't stop tinkering.",
			"Graduated with distinction from Carleton University's Computer Systems Engineering program. Finished my Master's of Applied Science in Electrical and Computer Engineering (February 2026) with a thesis on Neural SLAM and augmented reality for indoor 3D mapping.",
			"Right now I'm a Machine Learning Researcher at SAM3, building predictive models for health monitoring with multi-modal IoT sensors. Before that, I built real-time indoor 3D mapping systems at Carleton University using consumer drones, cloud-based SLAM, and AR visualization. I've also done DevOps at Magnet Forensics and spectrum engineering at Telesat.",
		],
		links: {
			linkedin: "https://www.linkedin.com/in/tom-sloan",
			portfolio: "https://tom-sloan.com",
			github: "https://github.com/Tom-Sloan",
		},
	},

	education: [
		{
			school: "Carleton University",
			degree: "Master of Applied Science - MASc",
			field: "Electrical and Computer Engineering",
			startDate: "October 2023",
			endDate: "February 2026",
			current: false,
			grade: "Graduate coursework: Machine Learning, Advanced ML, Deep Learning, Computer Vision",
			description:
				"Thesis: Indoor 3D Modeling Using Consumer Drones and Neural Simultaneous Localization and Mapping (SLAM) for Virtual Reality and a Cloud Architecture.\n\nBuilt a modular cloud-assisted SLAM framework for autonomous indoor mapping with a consumer drone (DJI Mini 3). Compared traditional visual-inertial (ORB-SLAM3) and neural SLAM (SLAM3R) approaches. Co-authored 3 IEEE papers presented at ICCE 2026, I2MTC 2025, and SAS 2025.",
			logo: "images/companies/carleton-university.png",
		},
		{
			school: "Carleton University",
			degree: "Bachelor of Engineering - BE",
			field: "Computer Systems",
			startDate: "September 2017",
			endDate: "December 2021",
			current: false,
			grade: "Graduated with distinction",
			description:
				"Computer Systems Engineering covering hardware, software, and systems design. Heavy focus on embedded systems and circuit design.",
			logo: "images/companies/carleton-university.png",
		},
	],

	experience: [
		{
			company: "SAM3",
			title: "Machine Learning Researcher",
			employmentType: "Full-time",
			location: "Ottawa, Ontario, Canada",
			startDate: "November 2025",
			endDate: "Present",
			current: true,
			description:
				"Building predictive models for fall detection, UTI risk, and sleep pattern analysis using multi-modal IoT sensors to monitor elderly patients. Developing time-series classification pipelines for the AGE-WELL-funded envisAGE aging-in-place study. Set up n8n automation pipelines for IoT sensor notifications. Built multi-step LLM pipelines with the Claude API for automated research workflows.",
			skills: [
				"PyTorch",
				"Time-Series Analysis",
				"IoT Sensors",
				"n8n",
				"Claude API",
				"RAG",
				"Python",
				"LLM",
			],
			logo: "images/companies/sam3.png",
		},
		{
			company: "Carleton University",
			title: "Research Assistant",
			employmentType: "Full-time",
			location: "Ottawa, Ontario, Canada",
			startDate: "October 2023",
			endDate: "November 2025",
			current: false,
			description:
				"Led the design and testing of a real-time indoor 3D mapping system using a consumer drone (DJI Mini 3), integrating monocular camera and IMU with cloud-based SLAM framework for AR applications. Trained and evaluated transformer-based neural SLAM model achieving 6.61 cm RMSE on Replica benchmark at 21 FPS inference. Co-authored 3 IEEE papers.",
			skills: [
				"Docker",
				"RabbitMQ",
				"React.js",
				"Unity",
				"SLAM",
				"AR",
				"Computer Vision",
				"Python",
				"PyTorch",
			],
			logo: "images/companies/carleton-university.png",
		},
		{
			company: "Magnet Forensics",
			title: "DevOps Engineer",
			employmentType: "Permanent Full-time",
			location: "Ottawa, Ontario, Canada",
			startDate: "April 2022",
			endDate: "June 2023",
			current: false,
			description:
				"Worked in a small team environment using DevOps tools including Jenkins, Linux, Python and PowerShell to help manage thousands of software builds a day on dozens of on-premise servers. Helped with the migration from on-premise to AWS cloud using CloudFormation and EC2.",
			skills: [
				"Jenkins",
				"Linux",
				"Python",
				"PowerShell",
				"AWS",
				"CloudFormation",
				"EC2",
			],
			logo: "images/companies/magnet-forensics.png",
		},
		{
			company: "Telesat",
			title: "Spectrum Engineering Co-Op",
			employmentType: "Full-time Internship",
			location: "Ottawa/Kanata, Ontario",
			startDate: "May 2020",
			endDate: "December 2021",
			current: false,
			description:
				"Made an alternative user interface and API in Python to interact with MATLAB giving the ability to directly use satellite XML data without requiring expensive MATLAB add-ons. Wrote extensive tests and code to analyze satellite spectrum use for international telecommunications regulations.",
			skills: ["Python", "MATLAB", "Telecommunications", "Satellite"],
			logo: "images/companies/telesat.jpg",
		},
		{
			company: "Carleton University",
			title: "Research/Teaching Assistant",
			employmentType: "Part-time",
			location: "Ottawa, Canada",
			startDate: "May 2018",
			endDate: "December 2021",
			current: false,
			description:
				"Designed and built prototype hardware for non-invasive monitoring of health markers (heart rate, respiration rate, body fluid flow) in older adults. Worked with faculty and grad students on health-monitoring research while TAing and running labs for computer engineering courses.",
			skills: [
				"Hardware Design",
				"Sensors",
				"Data Acquisition",
				"Python",
				"C/C++",
				"Teaching",
				"Research",
			],
			logo: "images/companies/carleton-university.png",
		},
	],

	projects: [
		{
			title: "M.A.Sc. Thesis: Neural SLAM for Indoor 3D Mapping",
			subtitle: "Electrical & Computer Engineering, Carleton University",
			description:
				"Built a modular, cloud-assisted SLAM framework for fully autonomous indoor mapping with a consumer drone (DJI Mini 3) that generates digital twins. Compared traditional visual-inertial SLAM (ORB-SLAM3) against neural SLAM (SLAM3R) and hit 6.61 cm RMSE on Replica benchmark at 21 FPS on an RTX 4070 Ti. The cloud architecture uses Docker, RabbitMQ, and React.js for real-time 3D reconstruction with AR headset streaming. Published at IEEE ICCE 2026, I2MTC 2025, and SAS 2025.",
			startDate: "October 2023",
			endDate: "February 2026",
			current: false,
			category: [
				{ tag: "AI Research", color: "#38BDF8" },
				{ tag: "Robotics", color: "#38BDF8" },
				{ tag: "Completed", color: "#22c55e" },
			],
			technologies: [
				"Python",
				"PyTorch",
				"ORB-SLAM3",
				"SLAM3R",
				"ROS 2",
				"Gymnasium",
				"PufferLib",
				"Reinforcement Learning",
				"Docker",
				"RabbitMQ",
				"React",
				"Three.js",
				"Unity",
				"Open3D",
				"C++",
				"CUDA",
				"DJI SDK",
				"Android",
				"Nginx",
				"Prometheus",
				"Grafana",
			],
			image: [
				"images/thesis/slam-reconstruction.png",
				"images/thesis/thesis-main-visualization.png",
			],
			link: "https://github.com/Tom-Sloan/WorldSystem",
			viewer3d: "viewer-3d.html",
			featured: true,
		},
		{
			title: "Multi-Agent AI System",
			subtitle: "RAG & LLM Orchestration",
			description:
				"Built dual-agent RAG system with SQLite vector DB and OpenAI embeddings indexing Obsidian vault and Google Drive. Semantic retrieval for context injection with agents coordinating via Telegram for task handoff. One agent handles calendar/email/research, the other handles coding tasks.",
			startDate: "October 2025",
			endDate: "Present",
			current: true,
			category: [
				{ tag: "LLM/Agents", color: "#8b5cf6" },
				{ tag: "In Progress", color: "#22c55e" },
			],
			technologies: [
				"OpenClaw",
				"Claude API",
				"Canva AI",
				"LangChain",
				"RAG",
				"SQLite",
				"OpenAI Embeddings",
				"Vector Search",
				"Raspberry Pi",
				"Python",
				"Telegram API",
			],
			image: null,
			link: "https://github.com/Tom-Sloan/llm-research-workflows",
			featured: true,
		},
		{
			title: "Pixelbar",
			subtitle: "Holographic Gaming Peripheral with Computer Vision",
			description:
				"A hardware + software gaming peripheral that displays in-game hotbar items as floating holograms inside physical glass prism cubes on your desk. Modular K9 beamsplitter prisms (expandable from 3 to 10 cubes) sit on a custom 3D-printed enclosure driven by an ESP32-S3 (8 MB PSRAM, 16 MB flash) with 1.3\" IPS 240x240 displays creating a Pepper's Ghost effect. AI-powered screen capture with a custom-trained YOLOv11n (1,771 self-labeled screenshots, 30+ games) detects the hotbar in any PC game, segments slots via multi-strategy OpenCV pipeline, and transmits identified items over USB-C serial at ~10 FPS per display. Includes a REST API developer platform for pushing arbitrary content to the cubes — stock tickers, stream alerts, system monitoring, or custom animations. Companion app built with Tauri (Rust + React) supports Windows, macOS, and Linux.",
			startDate: "February 2026",
			endDate: "Present",
			current: true,
			category: [
				{ tag: "Hardware", color: "#E05297" },
				{ tag: "Computer Vision", color: "#38BDF8" },
				{ tag: "Desktop App", color: "#8b5cf6" },
				{ tag: "In Progress", color: "#22c55e" },
			],
			technologies: [
				"ESP32-S3",
				"SPI",
				"Fusion 360",
				"3D Printing",
				"Tauri",
				"Rust",
				"React",
				"Vite",
				"Python",
				"FastAPI",
				"YOLOv11",
				"ONNX Runtime",
				"OpenCV",
				"PyTorch",
				"Framer Motion",
			],
			image: [
				"images/projects/pixelbar-openscad.png",
				"images/projects/pixelbar-terraria-closeup.jpg",
				"images/projects/pixelbar.png",
				"images/projects/pixelbar-minecraft.jpg",
				"images/projects/pixelbar-grounded.jpg",
				"images/projects/pixelbar-lego-fortnite.jpg",
				"images/projects/pixelbar-terraria.jpg",
			],
			link: "https://pixelbar.netlify.app",
			featured: true,
		},
		{
			title: "LeRobot SO-101",
			subtitle: "AI-Powered Robotic Arm with Imitation Learning",
			description:
				"Built and trained a Hugging Face LeRobot SO-101 6-DOF robotic arm with leader-follower teleoperation. 3D-printed the arm components and assembled them with Feetech STS3215 servo motors. Collected demonstration datasets through teleoperation and trained imitation learning policies on a Jetson Orin Nano for autonomous task execution. The leader arm records human demonstrations while the follower replicates movements, and I use that data to train end-to-end neural networks. Currently training in NVIDIA Isaac Sim for sim-to-real transfer.",
			startDate: "March 2026",
			endDate: "Present",
			current: true,
			category: [
				{ tag: "Robotics", color: "#38BDF8" },
				{ tag: "Hardware", color: "#E05297" },
				{ tag: "In Progress", color: "#22c55e" },
			],
			technologies: [
				"Python",
				"Jetson Orin Nano",
				"LeRobot",
				"Hugging Face",
				"PyTorch",
				"NVIDIA Isaac Sim",
				"3D Printing",
				"Feetech Servos",
				"Imitation Learning",
			],
			image: "images/projects/lerobot-demo.mp4",
			link: "https://huggingface.co/docs/lerobot/so101",
			featured: true,
		},
		{
			title: "drone-ai",
			subtitle: "Autonomous Drone Flight via Visual SLAM & Learned Motion Estimation",
			description:
				"Full-stack autonomous drone system built on ROS 2 Humble that flies GPS-free indoors using monocular visual SLAM and a SegNeXt neural network that extracts 6-DOF velocity from camera motion blur — replacing traditional IMU hardware entirely (image-as-an-IMU, ICCV 2025). Runs 10 containerized ROS 2 packages on a Jetson Orin Nano 8GB controlling a 17g BetaFPV Air65 via 250 Hz ExpressLRS radio. Custom ORB visual odometry with loop closure feeds into an Extended Kalman Filter fusing 15-25 Hz SLAM poses with 5-10 Hz learned velocity at 50 Hz output. 4-axis PID controller with ArUco metric scale estimation, geofence safety system, and optional LLM-powered autonomous flight via DimOS + Claude API. Supports distributed GPU offload over Tailscale VPN to a remote RTX 3090.",
			startDate: "October 2025",
			endDate: "Present",
			current: true,
			category: [
				{ tag: "Robotics", color: "#38BDF8" },
				{ tag: "AI Research", color: "#38BDF8" },
				{ tag: "Hardware", color: "#E05297" },
				{ tag: "In Progress", color: "#22c55e" },
			],
			technologies: [
				"ROS 2",
				"Python",
				"PyTorch",
				"Jetson Orin Nano",
				"Docker",
				"OpenCV",
				"SLAM",
				"CycloneDDS",
				"Go",
				"gRPC",
				"ExpressLRS",
				"Betaflight",
				"Foxglove",
				"Tailscale",
				"DimOS",
				"Claude API",
			],
			image: null,
			link: null,
			featured: true,
		},
		{
			title: "Discite",
			subtitle: "Personal Data Analytics Platform",
			description:
				"Built ETL pipelines automating GDPR data exports from Apple, Google, Discord, and Twitter. Parses heterogeneous zip archives with SQL queries for data analysis and visualization dashboards for cross-platform activity analysis.",
			startDate: "July 2024",
			endDate: "Present",
			current: false,
			category: [
				{ tag: "Data Analytics", color: "#10b981" },
				{ tag: "In Progress", color: "#22c55e" },
			],
			technologies: [
				"Electron",
				"React",
				"Python",
				"SQL",
				"ETL",
				"Data Visualization",
			],
			image: null,
			link: "https://tom-sloan.com/#projects",
			featured: false,
		},
		{
			title: "Portfolio MCP Server",
			subtitle: "Model Context Protocol Integration",
			description:
				"MCP server deployed as a Netlify serverless function so AI assistants can query my portfolio data directly. Exposes resources (profile, projects, experience, skills, education, certifications) and tools (search projects, filter experience, find skills) via the MCP protocol. AI assistants pull real-time data about my work instead of relying on stale training data.",
			startDate: "November 2025",
			endDate: "November 2025",
			current: false,
			category: [
				{ tag: "Web Development", color: "#FB4D3D" },
				{ tag: "AI Integration", color: "#8b5cf6" },
				{ tag: "Serverless", color: "#10b981" },
			],
			technologies: [
				"TypeScript",
				"Node.js",
				"Netlify",
				"Zod",
				"MCP SDK",
				"JSON-RPC",
			],
			image: "images/projects/MCP_in_action.mp4",
			link: "https://github.com/Tom-Sloan/Portfolio-Website",
			featured: true,
		},
		{
			title: "Smart Band Project",
			subtitle: "Sensors, PCB, and Bluetooth",
			description:
				"A personal project from university. I wanted to control smart devices with hand gestures using something like a Fitbit. I designed and fabricated a small PCB that reads motion data, classifies gestures, and sends commands to whatever device it's paired with.",
			startDate: "November 2019",
			endDate: "May 2021",
			current: false,
			category: [
				{ tag: "Hardware", color: "#E05297" },
				{ tag: "Programming", color: "#34D399" },
				{ tag: "IoT", color: "#00ADCC" },
			],
			technologies: [
				"C++",
				"PCB Design",
				"Bluetooth",
				"MQTT",
				"Arduino",
				"IMU Sensors",
				"Machine Learning",
			],
			image: "images/projects/smartBand.gif",
			link: "https://github.com/Tom-Sloan/Smart-Home-Project/tree/master/SmartBand",
			featured: true,
		},
		{
			title: "Smart Home Project",
			subtitle: "Full-Stack IoT with Custom PCBs",
			description:
				"Full-stack IoT system with custom sensor PCBs, firmware, AWS backend, and Firebase/Supabase for real-time sensor data storage and user account management. Created iOS smartphone app to control smart lights, switches, and blinds via NFC and BLE. SQL queries via Supabase for data persistence.",
			startDate: "November 2019",
			endDate: "May 2021",
			current: false,
			category: [
				{ tag: "Hardware", color: "#E05297" },
				{ tag: "Programming", color: "#34D399" },
				{ tag: "IoT", color: "#00ADCC" },
			],
			technologies: [
				"Swift",
				"C++",
				"Python",
				"iOS",
				"Bluetooth (BLE)",
				"NFC",
				"MQTT",
				"PCB Design",
				"Arduino",
				"AWS",
				"Firebase",
				"Supabase",
				"SQL",
			],
			image: "images/projects/smartHome.gif",
			link: "https://github.com/Tom-Sloan/Smart-Home-Project",
			featured: false,
		},
		{
			title: "Smart Pillbox",
			subtitle: "Medical Device",
			description:
				"Medication storage device mockup for adults with dementia and their caregivers. Medical practitioners can monitor medication consumption, set reminders and alarms, and lock the device if needed.",
			startDate: "August 2020",
			endDate: "April 2021",
			current: false,
			category: [
				{ tag: "Hardware", color: "#E05297" },
				{ tag: "IoT", color: "#00ADCC" },
			],
			technologies: [
				"C++",
				"Arduino",
				"PCB Design",
				"Sensors",
				"IoT",
				"Product Design",
			],
			image: "images/projects/pillbox1.jpg",
			link: null,
			featured: false,
		},
		{
			title: "LidarWorld",
			subtitle: "Interactive 3D LiDAR Sensor Simulation",
			description:
				"Interactive 3D LiDAR sensor simulation built with React Three Fiber and Three.js. Rooms are procedurally generated with randomized geometry and furniture. Sensors cast rays in real time to show detection coverage, and you can configure sensor types, adjust positioning, and rotate the view 360 degrees. Uses a grid-based spatial analysis system for coverage evaluation and a Leva control panel for tweaking parameters on the fly.",
			startDate: "December 2023",
			endDate: "November 2025",
			current: false,
			category: [
				{ tag: "Web Development", color: "#FB4D3D" },
				{ tag: "3D Graphics", color: "#8b5cf6" },
				{ tag: "Programming", color: "#34D399" },
			],
			technologies: [
				"React",
				"Three.js",
				"React Three Fiber",
				"TypeScript",
				"Leva",
				"WebGL",
			],
			image: "images/projects/lidarworld.png",
			link: null,
			featured: true,
		},
		{
			title: "Hound Dog - Family Card Game",
			subtitle: "Cross-Platform Mobile Card Game",
			description:
				"Turned a family card game from my childhood into a mobile app with React Native and Expo. Has real-time multiplayer via Socket.io, AI opponents with adjustable difficulty, and runs on both iOS and Android. Built with TypeScript, Zustand for state, and Expo Router for navigation.",
			startDate: "April 2025",
			endDate: "July 2025",
			current: false,
			category: [
				{ tag: "Mobile Dev", color: "#10b981" },
				{ tag: "Programming", color: "#34D399" },
				{ tag: "Web Development", color: "#FB4D3D" },
			],
			technologies: [
				"React Native",
				"TypeScript",
				"Expo",
				"Socket.io",
				"Zustand",
				"Expo Router",
			],
			image: "https://cdn-icons-png.flaticon.com/512/3159/3159310.png",
			link: null,
			featured: false,
		},
		{
			title: "Speakeasy - AI-Enhanced Social Podcast Platform",
			subtitle: "Full-Stack Mobile Podcast Application",
			description:
				"Full-stack mobile podcast app built with React Native, Expo, and a FastAPI backend. Pulls podcasts from the PodcastIndex API, stores data in PostgreSQL via Supabase, and uses Redis caching (cut API calls by 70%). Supports real-time audio streaming with background playback. JWT auth works for both registered and anonymous users, with Row-Level Security for multi-tenant data access. Includes podcast discovery, subscriptions, progress tracking, and social features.",
			startDate: "April 2025",
			endDate: "November 2025",
			current: false,
			category: [
				{ tag: "Mobile Dev", color: "#10b981" },
				{ tag: "Programming", color: "#34D399" },
				{ tag: "Web Development", color: "#FB4D3D" },
			],
			technologies: [
				"React Native",
				"TypeScript",
				"Expo",
				"FastAPI",
				"PostgreSQL",
				"Supabase",
				"Redis",
				"JWT",
				"Python",
			],
			image: "https://cdn-icons-png.flaticon.com/512/3845/3845874.png",
			link: null,
			featured: false,
		},
		{
			title: "Algorithmic Trading in Python",
			subtitle: "Quantitative Trading Strategies",
			description:
				"Three algorithmic trading strategies in Python: equal-weight portfolio rebalancing, momentum-based investing, and value investing. Each pulls real-time market data from the IEX Cloud API, calculates portfolio allocations with pandas and numpy, and spits out formatted Excel reports with buy recommendations for S&P 500 stocks.",
			startDate: "July 2020",
			endDate: "December 2020",
			current: false,
			category: [
				{ tag: "Programming", color: "#34D399" },
				{ tag: "Data Science", color: "#8b5cf6" },
			],
			technologies: [
				"Python",
				"Pandas",
				"NumPy",
				"IEX Cloud API",
				"Excel",
			],
			image: "https://cdn-icons-png.flaticon.com/512/2962/2962818.png",
			link: null,
			featured: false,
		},
		{
			title: "Reddit Client",
			subtitle: "Codecademy Full Stack Web Developer Portfolio Project",
			description:
				"Reddit client built with the Reddit API and React, using a Pinterest-style column layout for browsing posts. A diamond toggle in the corner changes the column count. Comes with preloaded subreddits and a search bar to pull up whatever you want.",
			startDate: "June 2020",
			endDate: "June 2020",
			current: false,
			category: [{ tag: "Web Development", color: "#FB4D3D" }],
			technologies: ["React", "JavaScript", "Reddit API", "HTML/CSS"],
			image: "images/projects/redditClient.png",
			link: null,
			featured: false,
		},
		{
			title: "Twitter Quote Bot",
			subtitle: "Automated quote plagiarism from my favourite authors",
			description:
				"A Python bot that scraped quotes from authors I like (Marcus Aurelius, Seneca) off quotes.net and posted one to my Twitter timeline daily. Deployed on Heroku. I turned it off so it'd stop spamming my feed, but the source code is on GitHub.",
			startDate: "April 2021",
			endDate: "April 2021",
			current: false,
			category: [
				{ tag: "Web Development", color: "#FB4D3D" },
				{ tag: "IoT", color: "#00ADCC" },
			],
			technologies: ["Python", "Twitter API", "Heroku", "Web Scraping"],
			image: "images/projects/twitterBot.png",
			link: "https://github.com/Tom-Sloan/TwitterBot",
			featured: false,
		},
		{
			title: "Automated Hydroponics System",
			subtitle: "PID-Controlled Nutrient Delivery with Sensor Fusion",
			description:
				"Fully automated drip hydroponic system built from PVC pipes and 3D-printed parts (Prusa MK3). An Arduino runs PID auto-tuning with Kalman filters to fuse readings from pH, electrical conductivity, water level, and temperature sensors. Peristaltic pumps dose nutrients precisely. A Raspberry Pi handles data logging and remote monitoring. Tested with lettuce and basil, with the eventual goal of growing Arabica coffee and green tea in Ottawa.",
			startDate: "July 2021",
			endDate: "August 2021",
			current: false,
			category: [
				{ tag: "Hardware", color: "#E05297" },
				{ tag: "Embedded", color: "#14B8A6" },
			],
			technologies: [
				"Arduino",
				"Raspberry Pi",
				"C++",
				"PID Control",
				"Kalman Filter",
				"3D Printing",
				"IoT",
			],
			image: null,
			link: null,
			featured: false,
		},
		{
			title: "Full Stack Development Course",
			subtitle: "Front End and Back End, including React and Redux",
			description:
				"Codecademy's Full Stack Development course, completed over summer 2021. Spent hundreds of hours on it and it got me into web development. I'd take breaks from the course to build actual projects, including my previous portfolio website.",
			startDate: "May 2021",
			endDate: "July 2021",
			current: false,
			category: [{ tag: "Web Development", color: "#FB4D3D" }],
			technologies: [
				"React",
				"Redux",
				"JavaScript",
				"Node.js",
				"HTML/CSS",
				"Express",
			],
			image: "https://www.credibll.com/build/images/campaign/full-stack-icons/junior-icon.png",
			link: null,
			featured: false,
		},
		{
			title: "Boat Refurbishment",
			subtitle: "New Hardware Implementation and Restoration",
			description:
				"My cousin and I restored an antique wooden speed boat that had rotted wood and missing parts. We repaired the motor, replaced the wood, and added some smart devices. The boat is seaworthy again after decades of sitting in a barn.",
			startDate: "July 2021",
			endDate: "August 2021",
			current: false,
			category: [
				{ tag: "Hardware", color: "#E05297" },
				{ tag: "IoT", color: "#00ADCC" },
			],
			technologies: ["IoT", "Hardware", "Marine Engineering"],
			image: "https://pluspng.com/img-png/row-boat-png-hd-small-fishing-boat-1754.png",
			link: null,
			featured: false,
		},
	],

	certifications: [
		{
			name: "Small Remotely Piloted Aircraft (VLOS) – Basic Operations",
			organization: "Transport Canada",
			issueDate: "March 2026",
			expirationDate: null,
			description:
				"Pilot certificate for basic operations of small remotely piloted aircraft systems within visual line-of-sight",
			credentialUrl: null,
			badgeImage: "images/certifications/transport-canada-rpas.png",
		},
		{
			name: "AWS Certified Machine Learning Engineer – Associate",
			organization: "Amazon Web Services (AWS)",
			issueDate: "November 2025",
			expirationDate: "November 2028",
			description:
				"Covers implementing ML workloads in production on AWS",
			credentialUrl:
				"https://www.credly.com/badges/9ae1b780-1c2c-4b5a-b25f-c9fad4707140",
			badgeImage: "images/certifications/aws-ml-engineer-associate.png",
		},
		{
			name: "AWS Security Specialty",
			organization: "Amazon Web Services (AWS)",
			issueDate: "October 2022",
			expirationDate: "October 2025",
			description: "Covers AWS security services and best practices",
			credentialUrl:
				"https://www.credly.com/badges/c5e97a97-e61e-41b4-aa37-e03b6d62a3fa",
			badgeImage: "images/certifications/aws-security-specialty.png",
		},
		{
			name: "AWS Certified SysOps Administrator – Associate",
			organization: "Amazon Web Services (AWS)",
			issueDate: "May 2022",
			expirationDate: "May 2025",
			description:
				"Covers deployment, management, and operations on AWS",
			credentialUrl: "https://www.credly.com/badges/",
			badgeImage: "images/certifications/aws-sysops-administrator.png",
		},
		{
			name: "AWS Certified Solutions Architect – Associate",
			organization: "Amazon Web Services (AWS)",
			issueDate: "January 2022",
			expirationDate: "January 2025",
			description:
				"Covers designing and implementing distributed systems on AWS",
			credentialUrl: "https://www.credly.com/badges/",
			badgeImage: "images/certifications/aws-solutions-architect.png",
		},
		{
			name: "AWS Certified Developer – Associate",
			organization: "Amazon Web Services (AWS)",
			issueDate: "February 2022",
			expirationDate: "February 2025",
			description:
				"Covers developing and maintaining applications on AWS",
			credentialUrl: "https://www.credly.com/badges/",
			badgeImage: "images/certifications/aws-developer.png",
		},
		{
			name: "AWS Cloud Practitioner",
			organization: "Amazon Web Services (AWS)",
			issueDate: "July 2020",
			expirationDate: "May 2025",
			description: "Foundational AWS cloud knowledge",
			credentialUrl:
				"https://www.credly.com/badges/c9afdb1e-f344-459e-b580-4534fae732d3",
			badgeImage: "images/certifications/aws-cloud-practitioner.png",
		},
		{
			name: "Canadian Securities Course (CSC)",
			organization: "Canadian Securities Institute (CSI)",
			issueDate: "August 2018",
			expirationDate: null,
			description:
				"Covers Canadian capital markets, securities, and investment products",
			credentialUrl:
				"https://www.credly.com/earner/earned/badge/565999ea-75d7-4ad5-996c-e33ca6f0e8e1",
			badgeImage: "images/certifications/canadian-securities-course.png",
		},
	],

	skills: {
		"Programming Languages": [
			{ name: "Python", icon: "images/skills/python.png" },
			{ name: "C/C++", icon: "images/skills/c-language.png" },
			{ name: "JavaScript", icon: "images/skills/javascript.png" },
			{ name: "TypeScript", icon: "images/skills/javascript.png" },
			{ name: "Rust", icon: "images/skills/rust.png" },
			{ name: "SQL", icon: "images/skills/mysql.png" },
		],
		"AI & Machine Learning": [
			{ name: "PyTorch", icon: "images/skills/pytorch.png" },
			{ name: "TensorFlow", icon: "images/skills/tensorflow.png" },
			{ name: "Hugging Face", icon: "images/skills/huggingface.png" },
			{ name: "scikit-learn", icon: "images/skills/sklearn.png" },
			{
				name: "Computer Vision",
				icon: "images/skills/computer-vision.png",
			},
			{ name: "SLAM", icon: "images/skills/slam.png" },
		],
		"LLM & Agents": [
			{ name: "RAG Pipelines", icon: "images/skills/rag.png" },
			{ name: "Vector Search", icon: "images/skills/vector-search.png" },
			{ name: "Prompt Engineering", icon: "images/skills/prompt-engineering.png" },
			{ name: "Claude API", icon: "images/skills/claude.png" },
			{ name: "OpenClaw", icon: "images/skills/openclaw.png" },
			{ name: "n8n", icon: "images/skills/n8n.png" },
		],
		"Cloud & DevOps": [
			{ name: "AWS", icon: "images/skills/aws.png" },
			{ name: "Docker", icon: "images/skills/docker.png" },
			{ name: "Jenkins", icon: "images/skills/jenkins.png" },
			{ name: "Linux", icon: "images/skills/linux.png" },
			{ name: "RabbitMQ", icon: "images/skills/rabbitmq.png" },
		],
		"Web Development": [
			{ name: "React", icon: "images/skills/react.png" },
			{ name: "Node.js", icon: "images/skills/nodejs.png" },
			{ name: "Redux", icon: "images/skills/redux.png" },
			{ name: "HTML/CSS", icon: "images/skills/html.png" },
			{ name: "Sass", icon: "images/skills/sass.png" },
		],
		"Databases & Backend": [
			{ name: "PostgreSQL", icon: "images/skills/postgresql.png" },
			{ name: "MongoDB", icon: "images/skills/mongodb.png" },
			{ name: "Supabase", icon: "images/skills/supabase.png" },
			{ name: "Firebase", icon: "images/skills/firebase.png" },
			{ name: "Git/GitHub", icon: "images/skills/github.png" },
		],
		"Robotics Platforms": [
			{ name: "ROS 2", icon: "images/skills/ros2.png" },
			{ name: "Gazebo", icon: "images/skills/gazebo.png" },
			{ name: "NVIDIA Isaac Sim", icon: "images/skills/isaac-sim.png" },
		],
		"Hardware & Embedded": [
			{ name: "PCB Design", icon: "images/skills/pcb-design.png" },
			{ name: "MCU", icon: "images/skills/microcontroller.png" },
			{ name: "Arduino", icon: "images/skills/arduino.png" },
			{ name: "FPGA", icon: "images/skills/fpga.png" },
			{ name: "Circuits", icon: "images/skills/circuit-design.png" },
		],
	},

	publications: [
		{
			title: "Drone-Based Indoor Mapping for Augmented Indoor 3D Modeling Using Neural Simultaneous Localization and Mapping (SLAM)",
			authors: ["T. Sloan", "B. Wallace", "R. Goubran"],
			conference:
				"2026 IEEE 44th International Conference on Consumer Electronics (ICCE)",
			location: "Dubai, UAE",
			year: 2026,
			pages: "1-6",
			image: "images/publications/neural-slam.png",
			keywords: [
				"Simultaneous localization and mapping",
				"Neural SLAM",
				"Indoor environment",
				"3D modeling",
				"Augmented reality",
				"Autonomous aerial vehicles",
				"Drones",
				"consumer drones",
				"indoor SLAM",
				"autonomous navigation",
				"real-time mapping",
				"DJI Mini 3",
				"UAV",
			],
		},
		{
			title: "Impact of Image Resolution on Controlling Drones Using Remote VR Headset Visualization and a Cloud Architecture",
			authors: ["T. Sloan", "B. Wallace", "R. Goubran"],
			conference: "2025 IEEE Sensors Applications Symposium (SAS)",
			location: "Newcastle, United Kingdom",
			year: 2025,
			pages: "1-6",
			doi: "10.1109/SAS65169.2025.11105183",
			url: "https://doi.org/10.1109/SAS65169.2025.11105183",
			image: "images/publications/latency.png",
			keywords: [
				"Visualization",
				"Image resolution",
				"Translation",
				"3G mobile communication",
				"Virtual reality",
				"Bandwidth",
				"Real-time systems",
				"Time measurement",
				"Usability",
				"Drones",
				"consumer drones",
				"autonomous navigation",
				"DJI Mini 3",
				"UAV",
				"Virtual Reality",
				"Teleoperation",
			],
		},
		{
			title: "System for Drone-Based Indoor Mapping for Augmented Reality",
			authors: ["T. Sloan", "B. Wallace", "R. Goubran"],
			conference:
				"2025 IEEE International Instrumentation and Measurement Technology Conference (I2MTC)",
			location: "Chemnitz, Germany",
			year: 2025,
			pages: "1-6",
			doi: "10.1109/I2MTC62753.2025.11079049",
			url: "https://doi.org/10.1109/I2MTC62753.2025.11079049",
			image: "images/publications/orbslam.png",
			keywords: [
				"Visualization",
				"Simultaneous localization and mapping",
				"Costs",
				"Autonomous aerial vehicles",
				"Real-time systems",
				"Indoor environment",
				"Standards",
				"Drones",
				"Ultra wideband technology",
				"Autonomous robots",
				"consumer drones",
				"indoor SLAM",
				"autonomous navigation",
				"real-time mapping",
				"DJI Mini 3",
				"UAV",
			],
		},
		{
			title: "Frequency Response of a Novel IR Based Pressure Sensitive Mat for Well-being Assessment",
			authors: [
				"B. Wallace",
				"J. Larivière-Chartier",
				"H. Liu",
				"T. Sloan",
				"R. Goubran",
				"F. Knoefel",
			],
			conference:
				"2020 IEEE 20th International Conference on Bioinformatics and Bioengineering (BIBE)",
			location: "Cincinnati, OH, USA",
			year: 2020,
			pages: "481-486",
			doi: "10.1109/BIBE50027.2020.00083",
			url: "https://doi.org/10.1109/BIBE50027.2020.00083",
			keywords: [
				"Optical losses",
				"Performance evaluation",
				"Prototypes",
				"Parallel processing",
				"Frequency response",
				"Sensors",
				"Sensor arrays",
				"pressure sensing",
				"unobtrusive sensors",
				"ambient sensing",
				"pressure sensor array",
				"IoT",
				"cloud processing",
			],
		},
	],

	resume: {
		path: "resume/Tom_Sloan_CV_Feb_2026.pdf",
		title: "Tom Sloan - Resume",
		description:
			"Download my full resume.",
	},
};

// Export for use in HTML
if (typeof module !== "undefined" && module.exports) {
	module.exports = portfolioData;
}
